const courses = [
  {
    _id: '1',
    courseId: '1',
    courseTitle: 'Introduction To Social Media Marketing',
    courseBrief: 'This couse contain a beginners guide to SMM',
    courseFee: 5,
    language: 'English',
    instructor:'Ritik Jain',
    timeRequired: ' 6 hr ',
    tags: ['Social', 'Media', 'Marketing'],
    rating: 4,
    image:
      'https://res.cloudinary.com/diczskxkx/image/upload/v1676156102/jjmhk8bkgrkezbbskieh.webp',
    courseModules: [
      {
        _id: '31',
        moduleId: '31',
        moduleTitle: 'Intro To Digital Marketing',
        chapterIds: [
          {
            courseChapterId: 'some data',
            chapterSequence: 'some data',
            chapterName: 'some data',
            chapterVideo: 'some data',
            timeRequired: 'some data',
          },
        ],
        moduleAssessmentIds: [],
        createdAt: '2023-04-11T10:57:06.082Z',
        updatedAt: '2023-04-11T10:57:06.082Z',
        __v: 0,
      },
      {
        _id: '32',
        moduleId: '32',
        moduleTitle: 'Intro To Social Media Marketing',
        chapterIds: [],
        moduleAssessmentIds: [],
        createdAt: '2023-04-11T10:57:06.083Z',
        updatedAt: '2023-04-11T10:57:06.083Z',
        __v: 0,
      },
    ],
    courseAssessmentIds: [],
    createdAt: '2023-04-11T10:57:06.487Z',
    updatedAt: '2023-04-11T10:57:06.487Z',
    __v: 0,
  },
  {
    _id: '2',
    courseId: '2',
    courseTitle: 'Introduction To Python Programming',
    courseBrief: 'This couse contain a beginners guide to Python',
    courseFee: 4,
    language: 'English',
    timeRequired: ' 8 hr ',
    instructor:'Kunal Jain', 
    tags: ['Python'],
    rating: 4.2,
    image:
      'https://res.cloudinary.com/diczskxkx/image/upload/v1676155679/azn1ngpqwcn5ounqm9ef.jpg',
    courseModules: [
      {
        _id: '41',
        moduleId: '41',
        moduleTitle: 'Intro to Python',
        chapterIds: [
          {
            courseChapterId: 'some data',
            chapterSequence: 'some data',
            chapterName: 'some data',
            chapterVideo: 'some data',
            timeRequired: 'some data',
          },
        ],
        moduleAssessmentIds: [],
        createdAt: '2023-04-11T10:57:06.082Z',
        updatedAt: '2023-04-11T10:57:06.082Z',
        __v: 0,
      },
      {
        _id: '42',
        moduleId: '42',
        moduleTitle: 'Python Setup',
        chapterIds: [],
        moduleAssessmentIds: [],
        createdAt: '2023-04-11T10:57:06.083Z',
        updatedAt: '2023-04-11T10:57:06.083Z',
        __v: 0,
      },
    ],
    courseAssessmentIds: [],
    createdAt: '2023-04-11T10:57:06.487Z',
    updatedAt: '2023-04-11T10:57:06.487Z',
    __v: 0,
  },
  {
    _id: '64412ac4f2bcaf8f626b4c1b',
    courseId: '64412ac4f2bcaf8f626b4c1b',
    courseTitle: 'Web Development: Basics To Advanced',
    courseBrief: 'This course contain a beginners guide to WebDev',
    courseFee: 0,
    language: 'English',
    timeRequired: ' 15 hr ',
    tags: ['WebDev', 'HTML', 'CSS', 'JS'],
    rating: 4.4,
    instructor:'Harsh Jain', 
    image:
      'https://res.cloudinary.com/diczskxkx/image/upload/v1681379408/MicrosoftTeams-image_3_wnp1bl.png',
    courseModules: [
      {
        _id: '1',
        moduleId: '1',
        moduleTitle: 'Intro to WebDev',
        chapterIds: [
          {
            courseChapterId: 'some data',
            chapterSequence: 'some data',
            chapterName: 'some data',
            chapterVideo: 'some data',
            timeRequired: 'some data',
          },
        ],
        moduleAssessmentIds: [],
        createdAt: '2023-04-11T10:57:06.082Z',
        updatedAt: '2023-04-11T10:57:06.082Z',
        __v: 0,
      },
      {
        _id: '2',
        moduleId: '2',
        moduleTitle: 'WebDev Basics - HTML, CSS, JS',
        chapterIds: [],
        moduleAssessmentIds: [],
        createdAt: '2023-04-11T10:57:06.083Z',
        updatedAt: '2023-04-11T10:57:06.083Z',
        __v: 0,
      },
    ],
    courseAssessmentIds: [],
    createdAt: '2023-04-11T10:57:06.487Z',
    updatedAt: '2023-04-11T10:57:06.487Z',
    __v: 0,
  },
  {
    _id: '4',
    courseId: '4',
    courseTitle: 'Data Science From Scratch Along With Projects',
    courseBrief: 'This couse contains a beginners guide to DS',
    courseFee: 6,
    language: 'English',
    timeRequired: ' 16 hr ',
    instructor:'Tanuj Jain', 
    tags: ['DS', 'ML', 'AI', 'DL'],
    rating: 4.6,
    image:
      'https://res.cloudinary.com/diczskxkx/image/upload/v1681403478/ds_do2sy2.jpg',
    courseModules: [
      {
        _id: '61',
        moduleId: '61',
        moduleTitle: 'Intro to DS',
        chapterIds: [
          {
            courseChapterId: 'some data',
            chapterSequence: 'some data',
            chapterName: 'some data',
            chapterVideo: 'some data',
            timeRequired: 'some data',
          },
        ],
        moduleAssessmentIds: [],
        createdAt: '2023-04-11T10:57:06.082Z',
        updatedAt: '2023-04-11T10:57:06.082Z',
        __v: 0,
      },
      {
        _id: '62',
        moduleId: '62',
        moduleTitle: 'DS Basics - ML, AI, DL',
        chapterIds: [],
        moduleAssessmentIds: [],
        createdAt: '2023-04-11T10:57:06.083Z',
        updatedAt: '2023-04-11T10:57:06.083Z',
        __v: 0,
      },
    ],
    courseAssessmentIds: [],
    createdAt: '2023-04-11T10:57:06.487Z',
    updatedAt: '2023-04-11T10:57:06.487Z',
    __v: 0,
  },
  {
    _id: '5',
    courseId: '5',
    courseTitle: 'Blockchain Technology By Industry Experts',
    courseBrief: 'This couse contains a beginners guide to Blockchain',
    courseFee: 10,
    language: 'English',
    timeRequired: ' 30 hr ',
    instructor:'Tanish Jain', 
    tags: [
      'Blockchain',
      'Crypto',
      'Ethereum',
      'Bitcoin',
      'SmartContracts',
      'DiFi',
    ],
    rating: 4.8,
    image:
      'https://res.cloudinary.com/diczskxkx/image/upload/v1681403479/bc_shvsah.png',
    courseModules: [
      {
        _id: '71',
        moduleId: '71',
        moduleTitle: 'Intro to Blockchain Technology',
        chapterIds: [
          {
            courseChapterId: 'some data',
            chapterSequence: 'some data',
            chapterName: 'some data',
            chapterVideo: 'some data',
            timeRequired: 'some data',
          },
        ],
        moduleAssessmentIds: [],
        createdAt: '2023-04-11T10:57:06.082Z',
        updatedAt: '2023-04-11T10:57:06.082Z',
        __v: 0,
      },
      {
        _id: '72',
        moduleId: '72',
        moduleTitle: 'Blockchain - SmartContracts',
        chapterIds: [],
        moduleAssessmentIds: [],
        createdAt: '2023-04-11T10:57:06.083Z',
        updatedAt: '2023-04-11T10:57:06.083Z',
        __v: 0,
      },
    ],
    courseAssessmentIds: [],
    createdAt: '2023-04-11T10:57:06.487Z',
    updatedAt: '2023-04-11T10:57:06.487Z',
    __v: 0,
  },
];

export default courses;
